# Generated by Django 3.2.20 on 2023-12-15 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0002_meetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 15, 16, 36, 55, 573649, tzinfo=utc), verbose_name='Дата начала'),
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='user',
        ),
        migrations.AddField(
            model_name='meetup',
            name='user',
            field=models.ManyToManyField(to='cli.User'),
        ),
    ]
