# Generated by Django 3.2.20 on 2023-12-16 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0009_alter_meetup_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 11, 31, 33, 895169, tzinfo=utc), verbose_name='Дата начала'),
        ),
    ]
